from pathlib import Path
from html import escape
import re
import build_courses as base

ROOT=Path(__file__).parent
ASSETS=ROOT/"diagrams"
ASSETS.mkdir(exist_ok=True)

extra={
"fisica":{"name":"Fisica","icon":"⚙",
"prima":[("Misure e grandezze","Grandezze fisiche, unità SI, strumenti, sensibilità e incertezza introducono il linguaggio quantitativo.","Una lunghezza di 12,4 cm misurata con scala millimetrata comunica valore e precisione.","Scrivere un numero senza unità o troppe cifre significative."),("Forze ed equilibrio","Una forza modifica moto o forma; si rappresenta con intensità, direzione e verso. Peso, attrito e reazione vincolare agiscono insieme.","Un libro fermo ha peso verso il basso e reazione del tavolo verso l'alto.","Pensare che se un corpo è fermo non agiscano forze."),("Pressione e fluidi","Pressione è forza per superficie; nei fluidi cresce con profondità e si trasmette in ogni direzione.","La stessa forza su area minore produce pressione maggiore.","Confondere forza e pressione."),("Calore e temperatura","Temperatura descrive lo stato termico; calore è energia trasferita per differenza di temperatura.","Un cucchiaio metallico conduce energia più rapidamente del legno.","Dire che un oggetto «contiene freddo».")],
"seconda":[("Moto","Sistema di riferimento, traiettoria, spazio, tempo e velocità media descrivono il moto.","120 km in 2 h corrispondono a 60 km/h.","Confondere velocità media con velocità in ogni istante."),("Leve e macchine semplici","Fulcro, potenza e resistenza; equilibrio dei momenti e vantaggio meccanico.","Una leva con braccio della potenza doppio richiede metà forza, idealmente.","Credere che una macchina faccia risparmiare lavoro ed energia."),("Suono","Vibrazioni, onde, frequenza, ampiezza, intensità, altezza e timbro.","Frequenza maggiore produce un suono più acuto.","Confondere altezza musicale e volume."),("Luce","Propagazione, ombra, riflessione, rifrazione, colori e lenti.","La matita appare spezzata nell'acqua per rifrazione.","Pensare che gli occhi emettano raggi per vedere.")],
"terza":[("Lavoro ed energia","Lavoro, potenza, energia cinetica e potenziale; conservazione e trasformazioni.","Sollevare una massa aumenta energia potenziale gravitazionale.","Dire che l'energia viene consumata invece di trasformata."),("Elettricità","Carica, corrente, tensione, resistenza, circuiti in serie e parallelo, legge di Ohm e sicurezza.","Con V=6 V e R=3 Ω, I=2 A.","Confondere corrente e tensione."),("Magnetismo ed elettromagnetismo","Poli, campo magnetico, corrente e campo, elettromagnete, motore e generatore.","Una bobina percorsa da corrente crea un campo magnetico.","Pensare che un polo magnetico possa essere isolato facilmente."),("Onde e radiazioni","Spettro elettromagnetico, frequenza, energia, usi e rischi delle radiazioni.","Radio e luce visibile sono entrambe onde elettromagnetiche.","Pensare che ogni radiazione sia ionizzante.")]} ,
"tecnologia-informatica":{"name":"Tecnologia e informatica","icon":"⌘",
"prima":[("Materiali","Legno, carta, vetro, ceramica, metalli e plastiche: origine, proprietà, lavorazione, uso e riciclo.","La scelta di un materiale confronta resistenza, massa, costo e impatto.","Scegliere solo per estetica."),("Disegno tecnico","Strumenti, tipi di linea, squadratura, scale, costruzioni geometriche e quotatura.","Scala 1:2 dimezza sul foglio ogni misura reale.","Confondere scala grafica e ingrandimento visivo."),("Algoritmi","Un algoritmo è una sequenza finita e non ambigua; diagrammi di flusso descrivono decisioni e ripetizioni.","Per trovare il maggiore: confronta, scegli, comunica.","Scrivere istruzioni interpretabili in più modi."),("Cittadinanza digitale","Identità, password, privacy, impronta digitale, netiquette e fonti.","Una passphrase lunga e unica è più robusta di una parola breve.","Condividere dati personali perché un sito sembra familiare.")],
"seconda":[("Strutture e abitazione","Strutture portanti, carichi, fondazioni, isolamento, impianti e sicurezza degli edifici.","Un triangolo irrigidisce un telaio perché non si deforma senza cambiare i lati.","Confondere parete divisoria e portante."),("Energia e macchine","Fonti, trasformazioni, rendimento, centrali e impatti ambientali.","Il rendimento confronta energia utile ed energia in ingresso.","Chiamare rinnovabile una fonte priva di impatti."),("Fogli di calcolo e dati","Celle, formule, riferimenti, ordinamento, grafici e controllo dei dati.","=SOMMA(B2:B8) evita calcoli manuali e si aggiorna.","Inserire numeri calcolati invece di formule."),("Programmazione visuale","Sequenza, evento, variabile, condizione, ciclo e debugging.","Un ciclo ripete un'azione finché la condizione cambia.","Correggere a caso senza isolare l'errore.")],
"terza":[("Sistemi produttivi","Settori economici, automazione, logistica, ciclo di vita e qualità.","L'analisi del ciclo di vita considera estrazione, uso e fine vita.","Valutare solo il prezzo di acquisto."),("Reti e Internet","Pacchetti, indirizzi, DNS, web, client-server, crittografia e sicurezza.","DNS traduce un nome leggibile in un indirizzo di rete.","Confondere Internet con il Web."),("Codice e problem solving","Funzioni, variabili, selezione, iterazione, test, modularità e documentazione.","Una funzione riduce ripetizioni e chiarisce lo scopo.","Testare solo il caso più semplice."),("Intelligenza artificiale e dati","Dati di addestramento, modelli, inferenza, bias, limiti, verifica e uso responsabile.","Un modello può riprodurre squilibri presenti nei dati.","Scambiare una risposta plausibile per una fonte.")]} ,
"arte":{"name":"Arte e immagine","icon":"◐",
"prima":[("Elementi visivi","Punto, linea, forma, colore, texture, luce e spazio costruiscono un'immagine.","Linee diagonali suggeriscono dinamismo; orizzontali quiete.","Descrivere solo il soggetto senza il linguaggio visivo."),("Colore","Primari, secondari, complementari, temperatura, saturazione e contrasti.","Blu e arancio sono complementari e aumentano il contrasto reciproco.","Pensare che esista un solo sistema di colori per ogni uso."),("Arte antica","Preistoria, Mesopotamia, Egitto, Grecia e Roma: funzione, tecnica e contesto.","Il tempio greco collega proporzione, culto e spazio civico.","Giudicare un'opera antica con criteri fotografici moderni."),("Composizione","Formato, equilibrio, ritmo, gerarchia, peso visivo e punto focale.","Un elemento isolato e contrastante attira l'attenzione.","Riempire ogni spazio senza gerarchia.")],
"seconda":[("Medioevo e Rinascimento","Romanico, Gotico, Umanesimo, prospettiva e centralità dell'uomo.","La prospettiva lineare organizza lo spazio con punto di fuga.","Ridurre il Rinascimento a «più realistico»."),("Barocco e luce","Dinamismo, teatralità, diagonali, chiaroscuro e rapporto con lo spettatore.","Il chiaroscuro guida lo sguardo e intensifica l'azione.","Confondere ogni forte contrasto con lo stesso stile."),("Prospettiva e volume","Linea d'orizzonte, punti di fuga, sovrapposizione, grandezza e modellato.","Parallele perpendicolari al quadro convergono verso il punto di fuga.","Collocare punti di fuga senza linea d'orizzonte coerente."),("Tecniche e progetto","Matita, tempera, collage, stampa, fotografia; ideazione, bozza, prova e revisione.","Una tavola di prove documenta scelte e correzioni.","Considerare la prima idea come soluzione definitiva.")],
"terza":[("Ottocento","Neoclassicismo, Romanticismo, Realismo, Impressionismo e trasformazioni moderne.","Gli impressionisti studiano percezione luminosa e vita contemporanea.","Definire ogni opera non rifinita «impressionista»."),("Avanguardie","Espressionismo, Cubismo, Futurismo, Dada, Surrealismo e astrazione.","Il Cubismo mostra più punti di vista nella stessa costruzione.","Pensare che deformazione significhi incapacità tecnica."),("Arte contemporanea","Pop art, installazione, performance, street art, video e pratiche partecipative.","Nell'installazione lo spazio e il percorso dello spettatore sono parte dell'opera.","Chiedere solo «è bello?» senza analizzare idea e contesto."),("Comunicazione visiva","Manifesto, fotografia, cinema, grafica, tipografia e lettura critica dei media.","In un manifesto gerarchia e contrasto rendono il messaggio leggibile.","Usare immagini senza verificarne fonte e diritti.")]} ,
"musica":{"name":"Musica","icon":"♫",
"prima":[("Suono e ascolto","Altezza, durata, intensità, timbro, silenzio e paesaggio sonoro.","Due strumenti sulla stessa nota differiscono per timbro.","Confondere intensità e altezza."),("Notazione","Pentagramma, chiave, note, figure, pause, battuta, metro e pulsazione.","In 4/4 quattro semiminime completano una battuta.","Confondere pulsazione e ritmo."),("Strumenti e voce","Famiglie strumentali, produzione del suono, registro e cura della voce.","Negli archi la corda vibra e la cassa amplifica.","Classificare solo in base al materiale."),("Musica antica e medievale","Funzioni rituali, monodia, canto gregoriano, nascita della polifonia e notazione.","La notazione rende trasmissibile una pratica prima prevalentemente orale.","Pensare al Medioevo come musicalmente uniforme.")],
"seconda":[("Ritmo e melodia","Pattern, sincopi, scale, intervalli, frase, tema e variazione.","Una variazione conserva un'identità trasformando ritmo o melodia.","Suonare note corrette senza fraseggio."),("Armonia di base","Accordo, consonanza, dissonanza, tonica e dominante a livello introduttivo.","La dominante crea tensione che spesso torna alla tonica.","Definire dissonanza come errore."),("Rinascimento e Barocco","Polifonia, madrigale, basso continuo, opera, concerto e fuga.","Nel concerto barocco il contrasto organizza gruppi e sezioni.","Confondere periodo storico e forma musicale."),("Esecuzione d'insieme","Ascolto reciproco, entrate, tempo, dinamica, gesto e prova efficace.","Provare lentamente isola ritmo e coordinazione.","Aumentare velocità prima della precisione.")],
"terza":[("Classico e Romantico","Forma-sonata, sinfonia, sviluppo tematico, virtuosismo, nazionalismo e musica a programma.","Un tema può essere frammentato e trasformato nello sviluppo.","Associare automaticamente ogni brano emotivo al Romanticismo."),("Novecento e popular music","Atonalità, jazz, blues, rock, elettronica, cinema e contaminazioni.","Il blues ha influenzato strutture, armonie e fraseggio di molti generi.","Raccontare i generi senza il loro contesto sociale."),("Tecnologia del suono","Microfono, registrazione, campionamento, MIDI, editing, copyright e ascolto sicuro.","MIDI descrive eventi musicali, non registra direttamente l'audio.","Confondere formato compresso e qualità assoluta."),("Analisi e progetto","Forma, organico, ritmo, melodia, armonia, timbro, contesto e interpretazione.","Un'analisi sostiene ogni impressione con un dettaglio udibile.","Scrivere «mi piace» senza evidenze musicali.")]} ,
"educazione-civica":{"name":"Educazione civica","icon":"§",
"prima":[("Regole e comunità","Regole, norme, sanzioni, responsabilità, scuola e partecipazione.","Una regola efficace chiarisce comportamento, motivo e conseguenza.","Confondere rispetto con obbedienza passiva."),("Diritti dell'infanzia","Dignità, uguaglianza, ascolto, protezione, istruzione e salute.","Un diritto è universale e comporta responsabilità istituzionali.","Considerare i diritti premi da meritare."),("Ambiente e beni comuni","Risorse, rifiuti, acqua, biodiversità e cura degli spazi condivisi.","Ridurre, riusare e riparare precedono spesso il riciclo.","Ridurre sostenibilità alla raccolta differenziata."),("Informazione","Fonte, autore, data, scopo, prova, opinione e verifica incrociata.","Due siti che copiano la stessa notizia non sono due conferme indipendenti.","Condividere dopo aver letto solo il titolo.")],
"seconda":[("Costituzione","Principi fondamentali, diritti, doveri e struttura della Costituzione italiana.","Uguaglianza formale e sostanziale richiedono azioni differenti.","Citare articoli senza spiegarne l'applicazione."),("Istituzioni","Comune, Regione, Stato, Parlamento, Governo, Presidente e Magistratura.","Separazione dei poteri limita concentrazioni e crea controlli.","Confondere Governo e Parlamento."),("Unione europea","Origini, valori, Parlamento, Commissione, Consiglio e cittadinanza europea.","Le istituzioni rappresentano interessi e funzioni differenti.","Attribuire all'UE ogni decisione nazionale."),("Media e partecipazione","Libertà di espressione, pluralismo, algoritmi, bolle informative e dialogo.","La libertà di espressione non elimina responsabilità e limiti di legge.","Confondere critica delle idee e attacco alla persona.")],
"terza":[("Democrazia e legalità","Stato di diritto, voto, rappresentanza, associazione, contrasto alle mafie e corruzione.","La legalità democratica include regole e tutela dei diritti.","Pensare che legalità significhi solo punizione."),("Diritti umani","Dichiarazione universale, discriminazioni, migrazioni, pace e giustizia internazionale.","I diritti sono interdipendenti: limitarne uno può indebolirne altri.","Parlare di gruppi senza ascoltarne le persone."),("Economia e lavoro","Lavoro dignitoso, imposte, welfare, consumo responsabile e finanza di base.","Le imposte finanziano servizi e redistribuzione secondo regole pubbliche.","Confondere prezzo basso e costo sociale basso."),("Sviluppo sostenibile","Agenda 2030, clima, disuguaglianze, indicatori e progettazione di azioni locali.","Un obiettivo utile ha indicatore, scadenza e responsabilità.","Proporre slogan senza misurare risultati.")]} ,
"terra-astronomia":{"name":"Scienze della Terra e astronomia","icon":"✦",
"prima":[("Orientamento celeste","Orizzonte, punti cardinali, moto apparente, ombre e osservazione sicura.","L'ombra solare cambia direzione e lunghezza durante il giorno.","Osservare il Sole direttamente."),("Sistema solare","Sole, pianeti, satelliti, asteroidi, comete, scale e gravità.","I pianeti orbitano perché inerzia e gravità agiscono insieme.","Disegnare distanze e diametri con la stessa scala senza avviso."),("Terra e Luna","Rotazione, rivoluzione, stagioni, fasi lunari ed eclissi.","Le stagioni dipendono dall'inclinazione dell'asse, non dalla distanza dal Sole.","Dire che le fasi sono l'ombra della Terra."),("Atmosfera e meteo","Strati, pressione, umidità, venti, nubi, precipitazioni e carte meteorologiche.","Aria che sale si espande, raffredda e può condensare.","Confondere previsione meteo e clima.")],
"seconda":[("Minerali e rocce","Proprietà dei minerali e ciclo di rocce magmatiche, sedimentarie e metamorfiche.","Una roccia può trasformarsi senza passare sempre dalla fusione.","Confondere roccia e minerale."),("Acque e suolo","Ciclo idrologico, falde, fiumi, erosione, suolo, fertilità e rischio.","Impermeabilizzare il terreno aumenta il deflusso superficiale.","Pensare che l'acqua sotterranea formi sempre grandi laghi."),("Clima","Fattori climatici, circolazione, biomi, dati e cambiamento climatico.","Una tendenza climatica richiede serie di dati lunghe.","Usare un giorno freddo per negare una tendenza globale."),("Risorse e rischi","Risorse rinnovabili/non rinnovabili, dissesto, prevenzione e protezione civile.","Rischio combina pericolosità, esposizione e vulnerabilità.","Credere che un evento naturale sia sempre un disastro.")],
"terza":[("Tettonica a placche","Struttura terrestre, convezione, margini, terremoti, vulcani e prove geologiche.","La distribuzione di terremoti delinea molti margini di placca.","Confondere magnitudo e intensità."),("Universo","Stelle, spettro, diagramma H-R, galassie, espansione e scale cosmiche.","Guardare lontano significa osservare luce partita nel passato.","Immaginare il Big Bang come esplosione in uno spazio vuoto."),("Gravità e orbite","Gravità universale, peso, massa, caduta e moto orbitale a livello concettuale.","In orbita si è in caduta libera continua, non senza gravità.","Dire che nello spazio non esiste gravità."),("Esplorazione e metodo","Telescopi, sonde, satelliti, dati, modelli, limiti e impatti tecnologici.","Osservazioni indipendenti rafforzano un modello astronomico.","Presentare ipotesi speculative come fatti accertati.")]}
}

subjects={**base.subjects,**extra}
grades=base.grades

# Due unità laboratoriali aggiuntive per ogni materia e anno.
for grade in grades:
 for ss,sub in subjects.items():
  first,second=sub[grade][0],sub[grade][1]
  sub[grade].extend([
   (f"Laboratorio autentico di {sub['name']}",
    f"Questa unità trasforma {first[0].lower()} e {second[0].lower()} in una sfida reale. Gli studenti osservano un problema, formulano domande, scelgono informazioni attendibili, costruiscono un prodotto e ne valutano l'efficacia con criteri condivisi.",
    f"La classe riceve una missione collegata a {first[0].lower()}: in gruppi assegna ruoli, prepara una soluzione verificabile, la presenta in novanta secondi e raccoglie un miglioramento proposto dai compagni.",
    "Dividere il lavoro senza condividere il ragionamento o valutare solo l'aspetto finale."),
   (f"Progetto interdisciplinare: {sub['name']} nel mondo",
    f"Un progetto guidato collega {sub['name'].lower()} a lingua, cittadinanza, dati e creatività. Si parte da una domanda autentica, si confrontano almeno due fonti, si produce una rappresentazione visiva e si difende una conclusione davanti a un pubblico.",
    f"Domanda-progetto: in quale modo {second[0].lower()} influenza una scelta della nostra comunità? Il prodotto finale comprende una mappa, un dato commentato, un esempio e una proposta concreta.",
    "Creare collegamenti decorativi, copiare informazioni o presentare conclusioni senza prove.")
  ])

def slugify(s):
 return re.sub(r"[^a-z0-9]+","-",s.lower()).strip("-")

def diagram(path,title,theory,accent):
 words=theory.split()
 labels=[" ".join(words[i:i+5]) for i in range(0,min(len(words),20),5)]
 while len(labels)<4: labels.append(title)
 boxes="".join(f'<g transform="translate({80+(i%2)*410} {150+(i//2)*210})"><rect width="330" height="130" rx="22" fill="#fff" stroke="{accent}" stroke-width="3"/><circle cx="42" cy="42" r="22" fill="{accent}"/><text x="42" y="49" text-anchor="middle" fill="white" font-size="18" font-weight="700">{i+1}</text><text x="78" y="42" font-size="17" font-weight="700" fill="#242421">{escape(title[:26])}</text><text x="30" y="86" font-size="14" fill="#555">{escape(labels[i])}</text><path d="M30 104 H290" stroke="#d9d4ca"/></g>' for i in range(4))
 arrows='<path d="M410 215 H485" stroke="#59636e" stroke-width="3" marker-end="url(#a)"/><path d="M245 280 V345" stroke="#59636e" stroke-width="3" marker-end="url(#a)"/><path d="M655 280 V345" stroke="#59636e" stroke-width="3" marker-end="url(#a)"/>'
 svg=f'''<svg xmlns="http://www.w3.org/2000/svg" width="900" height="650" viewBox="0 0 900 650" role="img" aria-labelledby="t d"><title id="t">{escape(title)}</title><desc id="d">Schema concettuale in quattro passaggi.</desc><defs><marker id="a" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="#59636e"/></marker></defs><rect width="900" height="650" rx="34" fill="#f2efe8"/><text x="80" y="82" font-family="Georgia,serif" font-size="34" fill="#242421">{escape(title)}</text><text x="80" y="112" font-family="Arial,sans-serif" font-size="14" fill="#6c6a63">Mappa concettuale · Zorix Education</text>{arrows}{boxes}</svg>'''
 path.write_text(svg,encoding="utf-8")

deep_blocks=[
("Obiettivi di apprendimento","Al termine del percorso dovrai saper definire il concetto con precisione, riconoscerlo in situazioni nuove, applicarlo con un procedimento controllabile e spiegare perché la soluzione è valida. La padronanza non coincide con la memoria: richiede scelta consapevole degli strumenti e capacità di correggersi."),
("Prerequisiti e punto di partenza","Prima di affrontare l'unità richiama ciò che già conosci. Scrivi tre parole associate al titolo, formula una previsione e annota un dubbio. Questo rende visibile la differenza tra idea iniziale e comprensione raggiunta, e permette di collegare il nuovo contenuto alle conoscenze precedenti."),
("Spiegazione passo per passo","Scomponi il tema in quattro mosse: osserva gli elementi, descrivi le relazioni, applica la regola o il modello, verifica il risultato. Ogni passaggio deve poter essere espresso con una frase completa. Se non riesci a spiegare un passaggio, torna alla definizione e costruisci un esempio più semplice."),
("Linguaggio specifico","Usare il lessico disciplinare evita ambiguità. Per ogni termine prepara una definizione, un esempio, un non-esempio e una relazione con un'altra parola. Non basta riconoscere il vocabolo: devi impiegarlo correttamente in una spiegazione e distinguerlo dai termini vicini."),
("Metodo di studio attivo","Leggi una porzione breve, chiudi il testo e ricostruiscila senza guardare. Confronta, correggi in un colore diverso e ripeti dopo un intervallo. Alterna richiamo, esercizio e spiegazione orale. Evidenziare da solo produce familiarità, ma non dimostra che saprai recuperare l'informazione durante una prova."),
("Dal semplice al complesso","Comincia da un caso privo di eccezioni, poi varia un elemento alla volta. Confronta ciò che resta invariato e ciò che cambia. Infine affronta un problema in cui la strategia non è dichiarata. Questo passaggio allena il trasferimento: la capacità di usare una conoscenza fuori dall'esempio studiato."),
("Connessioni interdisciplinari","Cerca un collegamento basato su un'idea reale, non sulla semplice presenza della stessa parola. Specifica il concetto comune, mostra come funziona nelle due discipline e indica anche una differenza. Un buon collegamento aggiunge comprensione; uno debole è solo un salto di argomento."),
("Strategia per la verifica","Leggi due volte la consegna, sottolinea il verbo operativo, identifica dati e vincoli, pianifica prima di rispondere. Durante lo svolgimento rendi visibile il ragionamento. Alla fine controlla coerenza, unità, lessico, completezza e corrispondenza tra domanda e risposta."),
("Analisi profonda del concetto","Distingui definizione, proprietà, procedura e campo di validità. La definizione stabilisce che cosa è il concetto; le proprietà descrivono come si comporta; la procedura indica come usarlo; il campo di validità chiarisce quando il modello funziona e quando occorre modificarlo. Questa distinzione impedisce di applicare meccanicamente una regola fuori contesto."),
("Costruzione del modello mentale","Immagina il contenuto come una rete, non come una lista. Al centro colloca l'idea principale; intorno disponi cause, conseguenze, esempi, controesempi e limiti. Etichetta ogni freccia con un verbo preciso. Se due nodi non possono essere collegati da una frase sensata, il rapporto non è ancora compreso."),
("Esempio, controesempio e caso limite","Un esempio mostra che una definizione si applica; un controesempio rivela che una generalizzazione è falsa; un caso limite mette alla prova i confini del modello. Costruirli autonomamente è uno degli strumenti più potenti per passare da una conoscenza fragile a una comprensione trasferibile."),
("Diagnosi degli errori","Quando una risposta è sbagliata, non limitarti a sostituirla. Classifica l'errore: lettura della consegna, richiamo della regola, scelta della strategia, esecuzione, linguaggio o controllo. Scrivi il punto esatto in cui il ragionamento devia e la domanda che avrebbe permesso di accorgersene."),
("Laboratorio pratico","Progetta una piccola attività osservabile: stabilisci scopo, materiali o fonti, procedura, dati da raccogliere e criterio di conclusione. Mantieni separati ciò che osservi e ciò che interpreti. Documenta anche risultati inattesi: spesso sono la parte più informativa dell'esperienza."),
("Comunicazione orale","Prepara un intervento in tre tempi: una domanda iniziale che orienta, uno sviluppo con due idee e un esempio, una sintesi che torna alla domanda. Parla usando parole-chiave, non un testo imparato a memoria. Allenati a rispondere a «come lo sai?» e «quando non vale?»."),
("Scrittura disciplinare","Una risposta completa contiene affermazione, evidenza e ragionamento. L'affermazione risponde; l'evidenza porta dato, regola o dettaglio; il ragionamento mostra perché l'evidenza sostiene la risposta. Usa connettivi causali, avversativi e conclusivi per rendere visibile la struttura logica."),
("Confronto e classificazione","Costruisci una tabella con criteri espliciti, evitando categorie sovrapposte. Per ogni elemento indica somiglianze, differenze e un criterio decisivo. Una classificazione è utile quando permette di prevedere o spiegare qualcosa, non quando si limita a distribuire etichette."),
("Trasferimento a un contesto nuovo","Cambia superficie al problema conservandone la struttura: modifica personaggi, numeri, lingua, ambiente o mezzo di rappresentazione. Poi identifica ciò che resta identico. Se sai riconoscere la stessa struttura sotto forme diverse, la conoscenza è disponibile per situazioni autentiche."),
("Percorso di recupero e potenziamento","Se il risultato è incerto, torna a definizioni ed esempi minimi, usa lo schema e completa esercizi a scelta guidata. Se la padronanza è solida, cerca eccezioni, confronta fonti, crea un problema e valuta due strategie. Recupero e potenziamento lavorano sullo stesso concetto a profondità differenti."),
]

def unit_page(grade,ss,sub,i,item,prev_link,next_link):
 title,theory,example,error=item
 gname,num,phase=grades[grade]
 accent=["#3762e9","#0e9ca8","#2f8d5b","#b5632f"][i%4]
 diag=f"diagrams/{grade}-{ss}-{i+1}.svg"
 diagram(ROOT/diag,title,theory,accent)
 diag2=f"diagrams/{grade}-{ss}-{i+1}-laboratorio.svg"
 diagram(ROOT/diag2,"Laboratorio: "+title,example,accent)
 engagement=f'''<section class="engagement" data-topic="{escape(title)}"><div class="hook"><p class="eyebrow">Gancio iniziale · 3 minuti</p><h2>La domanda che accende la classe</h2><p>Immagina di dover convincere un compagno che <strong>{escape(title.lower())}</strong> serve davvero fuori dalla scuola. Quale oggetto, notizia, scelta o esperienza useresti come prova?</p><button class="challenge-button" type="button">Estrai una sfida casuale</button><p class="challenge-output" aria-live="polite">Premi il pulsante: la classe avrà 60 secondi per rispondere.</p></div><div class="mission"><p class="eyebrow">Missione studenti · 15 minuti</p><h2>Osserva → ipotizza → prova → racconta</h2><ol><li>In coppia, scrivete una previsione senza consultare il testo.</li><li>Usate la mappa SVG per cercare un indizio che confermi o smentisca.</li><li>Create un mini esempio e un controesempio.</li><li>Spiegate la scoperta in una frase di massimo venti parole.</li></ol></div><details class="teacher-panel"><summary>Modalità docente: scaletta pronta da presentare</summary><div class="teacher-grid"><div><strong>0–3 min · Sorprendere</strong><p>Mostra soltanto il titolo e raccogli tre ipotesi senza correggere.</p></div><div><strong>3–10 min · Modellare</strong><p>Pensa ad alta voce usando l'esempio: {escape(example)}</p></div><div><strong>10–25 min · Far fare</strong><p>Avvia la missione in coppia; chiedi a chi osserva di annotare il ragionamento.</p></div><div><strong>25–35 min · Confrontare</strong><p>Metti due soluzioni alla lavagna e fai cercare una somiglianza e una differenza.</p></div><div><strong>35–45 min · Consolidare</strong><p>Nomina il concetto, correggi questo errore: {escape(error)}</p></div><div><strong>Ultimi 3 min · Verificare</strong><p>Exit ticket: «Prima pensavo…, ora penso…, mi resta da capire…».</p></div></div></details><div class="quick-quiz"><p class="eyebrow">Quiz lampo</p><h2>Vero, falso o dipende?</h2><p>{escape(theory)}</p><button type="button" class="reveal-answer">Mostra come argomentare</button><p class="answer" hidden>Non basta scegliere: cita la definizione, costruisci un caso e indica il limite. Una risposta eccellente usa «perché» e «tuttavia».</p></div></section>'''
 blocks="".join(f'''<section class="lesson-block"><p class="eyebrow">{escape(h)}</p><h2>{escape(title)}: {escape(h.lower())}</h2><p>{escape(text)} Nel caso di <strong>{escape(title.lower())}</strong>, il nucleo da conservare è questo: {escape(theory)}</p><p>Prova ora a riformulare il punto usando il connettivo «perché», poi con «quindi» e infine con «tuttavia». Le tre formulazioni obbligano a distinguere causa, conseguenza e limite del modello.</p></section>''' for h,text in deep_blocks)
 glossary="".join(f"<tr><th>{escape(w.strip('.,;:').capitalize())}</th><td>Termine chiave da definire nel contesto di {escape(title)} e da collegare al modello dell'unità.</td><td>Scrivi un esempio e un non-esempio.</td></tr>" for w in theory.split()[:12])
 exercises="".join(f'''<li><strong>Livello {n}.</strong> {q} <details><summary>Traccia di soluzione</summary><p>Riparti dalla definizione: {escape(theory)} Usa l'esempio «{escape(example)}» come modello di procedimento, modificando dati e contesto. Concludi con un controllo esplicito.</p></details></li>''' for n,q in enumerate([
  f"Definisci {title} in massimo quattro righe e aggiungi un esempio.",
  f"Confronta un caso corretto di {title} con un caso che sembra simile ma non lo è.",
  "Costruisci una mappa con quattro nodi e tre relazioni etichettate.",
  f"Spiega perché questo errore è plausibile e come correggerlo: {error}",
  "Applica l'idea a una situazione quotidiana non citata nella pagina.",
  "Formula una domanda da verifica e scrivi i criteri di una risposta eccellente.",
  "Collega l'unità a un'altra materia indicando somiglianza e differenza.",
  "Prepara una spiegazione orale di tre minuti con apertura, sviluppo e sintesi."
 ],1))
 return f'''<!doctype html><html lang="it"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} · {sub["name"]} · {gname}</title><meta name="description" content="Unità didattica approfondita: {escape(title)}."><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="course.css"><link rel="stylesheet" href="unit.css"><link rel="stylesheet" href="theme-cute.css"></head><body>{base.header()}<main><section class="unit-hero" style="--accent:{accent}"><a class="back" href="{grade}-{ss}.html">← {sub["name"]}</a><p class="eyebrow">{gname} · Unità {i+1}</p><h1>{escape(title)}</h1><p>{escape(theory)}</p></section><nav class="unit-nav" aria-label="Navigazione tra unità">{prev_link}<a href="{grade}-{ss}.html">Indice del corso</a>{next_link}</nav>{engagement}<article class="lesson"><section class="visual"><img src="{diag}" alt="Mappa concettuale di {escape(title)}"><p>Segui le frecce, poi prova a ridisegnare lo schema senza guardare.</p><img src="{diag2}" alt="Schema di laboratorio di {escape(title)}"><p>Usa il secondo schema per progettare una spiegazione o un’attività.</p></section><section class="lesson-block key"><p class="eyebrow">Il concetto centrale</p><h2>Che cosa devi davvero capire</h2><p>{escape(theory)}</p><div class="worked"><h3>Esempio completamente guidato</h3><p>{escape(example)}</p><ol><li>Individua la domanda e separa i dati utili.</li><li>Richiama la definizione pertinente e giustifica la scelta.</li><li>Procedi un passo alla volta, nominando l'operazione mentale svolta.</li><li>Controlla il risultato con un metodo differente o un caso limite.</li><li>Scrivi una frase conclusiva che risponda esattamente alla domanda.</li></ol></div><aside><strong>Errore ad alta frequenza</strong><p>{escape(error)}</p><p>Per evitarlo, fermati prima del calcolo o della risposta e chiediti quale definizione autorizza il passaggio.</p></aside></section>{blocks}<section class="lesson-block"><p class="eyebrow">Glossario operativo</p><h2>Le parole da saper usare</h2><div class="table-wrap"><table><thead><tr><th>Parola</th><th>Significato operativo</th><th>Prova di padronanza</th></tr></thead><tbody>{glossary}</tbody></table></div></section><section class="lesson-block exercises"><p class="eyebrow">Laboratorio</p><h2>Esercizi graduati con tracce</h2><ol>{exercises}</ol></section><section class="lesson-block final-check"><p class="eyebrow">Autovalutazione</p><h2>Quando l'unità è davvero acquisita</h2><ul><li>So spiegare il tema senza leggere.</li><li>So usare correttamente almeno otto parole del glossario.</li><li>So risolvere un caso nuovo e motivare ogni passaggio.</li><li>So riconoscere e correggere l'errore tipico.</li><li>So creare un collegamento interdisciplinare non forzato.</li></ul></section></article></main><footer><span>© Zorix Education</span><a href="index.html">Indice generale</a></footer><script src="interactive.js"></script></body></html>'''

def subject_index(grade,ss,sub):
 gname,num,phase=grades[grade]
 cards=[]
 for i,item in enumerate(sub[grade]):
  cards.append(f'''<a class="unit-card" href="{grade}-{ss}-{i+1}.html"><span>{i+1:02}</span><div><h2>{escape(item[0])}</h2><p>{escape(item[1])}</p></div><b>Apri l'unità →</b></a>''')
 return f'''<!doctype html><html lang="it"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{sub["name"]} · {gname}</title><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="course.css"><link rel="stylesheet" href="unit.css"><link rel="stylesheet" href="theme-cute.css"></head><body>{base.header()}<main><section class="course-hero"><a class="back" href="index.html#{grade}">← Indice generale</a><p class="eyebrow">{num} · {gname} · {phase}</p><h1>{sub["name"]}</h1><p class="course-lead">Sei unità indipendenti, ciascuna con attività coinvolgenti, guida docente e spiegazione estesa, schema SVG, esempio guidato, glossario, esercizi e autovalutazione.</p></section><section class="unit-index">{''.join(cards)}</section></main><footer><span>© Zorix Education</span><a href="index.html">Indice generale</a></footer><script src="interactive.js"></script></body></html>'''

for grade in grades:
 for ss,sub in subjects.items():
  units=sub[grade]
  for i,item in enumerate(units):
   prev_link=f'<a href="{grade}-{ss}-{i}.html">← Precedente</a>' if i else '<span></span>'
   next_link=f'<a href="{grade}-{ss}-{i+2}.html">Successiva →</a>' if i<len(units)-1 else '<span></span>'
   (ROOT/f"{grade}-{ss}-{i+1}.html").write_text(unit_page(grade,ss,sub,i,item,prev_link,next_link),encoding="utf-8")
  (ROOT/f"{grade}-{ss}.html").write_text(subject_index(grade,ss,sub),encoding="utf-8")

groups=[]
for grade,(gname,num,phase) in grades.items():
 cards=''.join(f'''<a class="catalog-card" href="{grade}-{ss}.html"><span class="catalog-icon">{sub["icon"]}</span><div><h3>{sub["name"]}</h3><p>6 unità separate · schemi SVG · esercizi</p></div><span>↗</span></a>''' for ss,sub in subjects.items())
 groups.append(f'''<section class="catalog-year" id="{grade}"><div class="catalog-heading"><p class="eyebrow">{num} · {phase}</p><h2>{gname}</h2><p>{len(subjects)} materie, ognuna divisa in quattro unità HTML indipendenti.</p></div><div class="catalog-grid">{cards}</div></section>''')
base_page=f'''<!doctype html><html lang="it"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Zorix Education — Biblioteca completa</title><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="course.css"><link rel="stylesheet" href="unit.css"><link rel="stylesheet" href="theme-cute.css"></head><body>{base.header()}<main><section class="catalog-hero"><p class="eyebrow">Biblioteca completa · {len(subjects)*3*6} unità</p><h1>Ogni materia.<br><em>Ogni unità.</em></h1><p>Una biblioteca offline in italiano: {len(subjects)} materie per tre anni, con una pagina dettagliata e un diagramma SVG per ogni singola unità.</p><div class="quick"><a href="#prima">Prima media</a><a href="#seconda">Seconda media</a><a href="#terza">Terza media</a></div></section>{''.join(groups)}</main><footer><span>© Zorix Education</span><a href="#">Torna su ↑</a></footer><script src="interactive.js"></script></body></html>'''
(ROOT/"index.html").write_text(base_page,encoding="utf-8")

def technical_drawing_svg(laboratory=False):
 title="Laboratorio di disegno tecnico" if laboratory else "Disegno tecnico"
 panels=[
  ("1 · STRUMENTI","Matita H/HB · righello","squadre · compasso"),
  ("2 · TIPI DI LINEA","continua: contorni","tratteggio: elementi nascosti"),
  ("3 · SCALA 1:2","reale 100 mm","disegno 50 mm"),
  ("4 · QUOTATURA","linee di misura","frecce · valore · unità")
 ]
 if laboratory:
  panels=[
   ("1 · OSSERVA","individua forma e misure","scegli la vista principale"),
   ("2 · IMPOSTA","squadra il foglio","stabilisci scala e margini"),
   ("3 · COSTRUISCI","traccia linee leggere","controlla parallelismi"),
   ("4 · COMPLETA","ripassa e quota","verifica · pulisci · firma")
  ]
 boxes=[]
 for i,(head,a,b) in enumerate(panels):
  x=60+(i%2)*420; y=150+(i//2)*220
  boxes.append(f'''<g transform="translate({x},{y})"><rect x="0" y="0" width="360" height="170" rx="18" fill="#ffffff" stroke="#0e9ca8" stroke-width="3"/><rect x="0" y="0" width="360" height="46" rx="18" fill="#0e9ca8"/><rect x="0" y="28" width="360" height="18" fill="#0e9ca8"/><text x="22" y="30" font-family="Arial, sans-serif" font-size="17" font-weight="700" fill="#ffffff">{head}</text><text x="22" y="82" font-family="Arial, sans-serif" font-size="16" fill="#242421">{a}</text><text x="22" y="112" font-family="Arial, sans-serif" font-size="16" fill="#242421">{b}</text><line x1="22" y1="137" x2="330" y2="137" stroke="#94a3b8" stroke-width="2"/><circle cx="22" cy="137" r="5" fill="#2563eb"/><circle cx="330" cy="137" r="5" fill="#22c55e"/></g>''')
 return f'''<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="900" height="650" viewBox="0 0 900 650"><title>{title}</title><desc>Schema tecnico compatibile con browser mobili.</desc><rect x="0" y="0" width="900" height="650" fill="#f2efe8"/><text x="60" y="72" font-family="Georgia, serif" font-size="38" fill="#242421">{title}</text><text x="60" y="106" font-family="Arial, sans-serif" font-size="15" fill="#6c6a63">Zorix Education · schema SVG 1.1</text>{''.join(boxes)}</svg>'''

(ASSETS/"prima-tecnologia-informatica-2.svg").write_text(technical_drawing_svg(False),encoding="utf-8")
(ASSETS/"prima-tecnologia-informatica-2-laboratorio.svg").write_text(technical_drawing_svg(True),encoding="utf-8")
print(f"Generati {len(subjects)*3} indici di materia, {len(subjects)*3*6} unità HTML e {len(subjects)*3*6} diagrammi SVG.")
